export { default as AuthRoute } from './auth'
export { default as AuthorRoute } from './author'
export { default as BookRoute } from './book'
export { default as CouponRoute } from './coupon'
export { default as MailRoute } from './mail'
export { default as OrderRoute } from './order'
export { default as TokenRoute } from './token'
export { default as UserRoute } from './user'